---
- name: CREATE app's namespace
  community.kubernetes.k8s:
    kind: Namespace
    name: "{{ extra_app.name }}"
    kubeconfig: "config.yaml"

# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#deployment-v1-apps
- name: CREATE Deployment per component
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'deployment-arcadia-component.yaml') | from_yaml }}"
    kubeconfig: "config.yaml"
  loop: "{{ extra_app.components }}"

# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#servicespec-v1-core
- name: CREATE Service per component
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'service_nodeport-arcadia.yaml') | from_yaml }}"
    kubeconfig: "config.yaml"
  loop: "{{ extra_app.components }}"

# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#secret-v1-core
- name: CREATE Secret
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'secret-app.yaml') | from_yaml }}"
    kubeconfig: "config.yaml"

- name: SET WAF policy - variables
  set_fact:
    url_waf_policy_core: "https://raw.githubusercontent.com/nergalex/f5-nap-policies/master/policy/core/secure_{{ extra_waf_policy_level }}.yaml"
    url_waf_policy_modifications: "https://raw.githubusercontent.com/nergalex/f5-nap-policies/master/policy/modifications/{{extra_app.name}}.{{extra_app.domain}}.json"
    var_waf_version: "{{ 1000 | random | to_uuid }}"

- name: WAF policy version ID
  debug:
    var: var_waf_version

- name: CREATE external WAF policy
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'policy-external-generic.yaml') | from_yaml }}"
    kubeconfig: "config.yaml"

# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingress-v1beta1-extensions
- name: CREATE Ingress external - master
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'ingress-external_master.yaml') | from_yaml }}"
    kubeconfig: "config.yaml"
    force: yes
    apply: yes
    
- name: CREATE Ingress external - minions
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'ingress-external_minion.yaml') | from_yaml }}"
    kubeconfig: "config.yaml"
    force: yes
    apply: yes
  loop: "{{ extra_app.components}}"


...