apiVersion: v1
kind: Deployment
metadata:
  name: "{{ item.name }}"
  namespace: "{{ extra_app.name }}"
  labels:
    app: "{{ extra_app.name }}"
    service: "{{ item.name }}"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: "{{ extra_app.name }}"
      service: "{{ item.name }}"
  template:
    metadata:
      labels:
        app: "{{ extra_app.name }}"
        service: "{{ item.name }}"
    spec:
      containers:
      - name: "{{ item.name }}"
        env:
        - name: service_name
          value: "{{ item.name }}"
        image: "{{ stats_acr_login_server }}/{{ extra_app.name }}-{{ item.name }}:1.0.0"
        ports:
        - containerPort: 80








