apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ extra_app.name }}-ingress-external"
  namespace: "{{ extra_app.name }}"
  labels:
    app: "{{ extra_app.name }}"
    policy_target: external
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    appprotect.f5.com/app-protect-policy: "external-ingress-controller/waf-policy-external-{{ extra_app.name }}-v{{ var_waf_version }}"
    appprotect.f5.com/app-protect-enable: "True"
    appprotect.f5.com/app-protect-security-log-enable: "True"
    appprotect.f5.com/app-protect-security-log: "external-ingress-controller/naplogformat"
    appprotect.f5.com/app-protect-security-log-destination: "syslog:server={{ extra_elk }}:5144"
spec:
  tls:
  - hosts:
    - "{{ extra_app.name }}.{{ extra_app.domain }}"
    secretName: "external-ingress-controller/{{ extra_app.name }}-secret-tls"
  rules:
  - host: "{{ extra_app.name }}.{{ extra_app.domain }}"
    http:
      paths:
{% for component in extra_app.components %}
        - path: "{{ component.location }}"
          pathType: Prefix
          backend:
            serviceName: "{{ component.name }}"
            servicePort: 80
{% endfor %}







