apiVersion: v1
kind: Secret
metadata:
  name: "{{ extra_app.name }}-secret-tls"
  namespace: "{{ extra_app.name }}"
type: Opaque
data:
  tls.crt: {{ extra_app_tls_crt | b64encode }}
  tls.key: {{ extra_app_tls_key | b64encode }}









