apiVersion: v1
kind: Service
metadata:
  name: "{{ item.name }}"
  namespace: "{{ extra_app.name }}"
  labels:
    app: "{{ extra_app.name }}"
    service: "{{ item.name }}"
spec:
  type: NodePort
  ports:
  - name: "{{ item.name }}-80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: "{{ extra_app.name }}"
    service: "{{ item.name }}"
